### ISSUE TITLE
useBanner flag isn't being followed

### ISSUE THREAD

**Issue by Ron-Kuper-Bose** [Bose/go-gin-logrus#22]
It seems the `useBanner` parameter isn't being respected. We have some code that tries to use the logger with useBanner=false and we still get a banner.

I think line 52 in middleware.go is the culprit - you create a logging buffer WithBanner(true) unconditionally.

**Comment by Jim-Lambert-Bose** [comment]
fixed in: https://github.com/Bose/go-gin-logrus/releases/tag/v2.0.8
